### ISSUE TITLE
Add driver functions( main() function )

### ISSUE THREAD

**Issue by amarnathsama** [the-hyp0cr1t3/CC#1]
I read the snippets but couldn't understand how to use it, please add a driver function or comments on how to use snippets in code.

**Comment by the-hyp0cr1t3** [comment]
These are snippets, and are not meant to be full programs. That said, I have gone through everything and added some comments and links to resources which summarize the concepts where applicable. Usage should be apparent and fairly obvious thereafter. If there's anything specific that you'd like me to explain, let me know.
