### ISSUE TITLE
GUIDE

### ISSUE THREAD

**Issue by ArunSharmaLearning** [the-hyp0cr1t3/CC#10]
Can anyone guide , how to run random tree generate code.
Simply copying the code is not working,

**Comment by the-hyp0cr1t3** [comment]
Could you please describe in a little more detail what it is that's not working? What error are you getting?

If it is a compilation error, try compiling with ‘-std=c++17’ or ‘-std=gnu++17’.

**Comment by the-hyp0cr1t3** [comment]
Should also compile with `-std=c++14` or `-std=gnu++14` now.

**Comment by ArunSharmaLearning** [comment]
bro i am running this in VS code and online C++ compiler.
where should i run this or i need to install some special compiler as u mentioned

**Comment by the-hyp0cr1t3** [comment]
> bro i am running this in VS code and online C++ compiler.
> where should i run this or i need to install some special compiler as u mentioned
> 

You have to set the C++ standard to 17 or above (14 also works but with warnings). [This] (https://stackoverflow.com/questions/66680147/how-to-change-c-version-being-used-by-vscode) might help. If you are using a separate extension, then consult its documentation for the same.

**Comment by ArunSharmaLearning** [comment]
#include <bits/stdc++.h>
using namespace std;
 
 i think you have not included these lines

**Comment by the-hyp0cr1t3** [comment]
It is a snippet. It is assumed that any external dependencies have already been included and are present. If you still have issues with the code, let me know. Otherwise do close the issue.
