### ISSUE TITLE
Suggestion on Two Pointers

### ISSUE THREAD

**Issue by AntennaeVY** [the-hyp0cr1t3/CC#11]
The first quoted resource is not available. You need to subscribe to the author's quora to be able to see the article. Therefore I'd suggest citing other resources or taking into consideration removing this one.

Quoted source:
https://www.quora.com/q/techparoksha/The-Two-Pointer-Algorithm

**Comment by the-hyp0cr1t3** [comment]
I think this quora article is gold, so I'll keep it there for whoever can access it. In case you are not able to, the CF Edu on 2-pointers also is a great learning resource for the same (linked as secondary material). Thanks for bringing it to my notice :)
