### ISSUE TITLE
how can i change merge and build function (lazy segment tree)

### ISSUE THREAD

**Issue by MdNihal05** [the-hyp0cr1t3/CC#19]
as we create merge/combine function to handle queries like sum ,  gcd , lcm  , min , max in [l,r]
( i use kactl templete for classic )
or change [l,r]=x 
how can i change in this in your lazy templete

```c++
class SegmentTree {
    typedef int T;
    static constexpr T unit = INT_MAX;        //change this {INT_MAX,INT_MIN,0}
    T fun(T a, T b) { return a & b; } // (any associative fn)
    vector<T> s; int n;
public:
    SegmentTree(int n = 0, T def = unit) : s(2 * n, def), n(n) {}
    void update(int pos, T val) {
        for (s[pos += n] = val; pos /= 2;)
            s[pos] = fun(s[pos * 2], s[pos * 2 + 1]);
    }
    T query(int b, int e) { // query [b, e)
        T ra = unit, rb = unit;
        for (b += n, e += n; b < e; b /= 2, e /= 2) {
            if (b % 2) ra = fun(ra, s[b++]);
            if (e % 2) rb = fun(s[--e], rb);
        }
        return fun(ra, rb);
    }
};  
it has fun to change accordingly

**Comment by the-hyp0cr1t3** [comment]
Not sure if I understood your query correctly, but you have to modify `SegmentTree::fun` to perform whatever operation you need to.

```c++
T fun(T a, T b) { return std::min(a, b); }
```

**Comment by MdNihal05** [comment]
Thanks for considering this and Sorry that I was not clear
I know how to use this template as i learned classic segment trees


I provided this code as reference
Iam asking about the code  in your repository
As I am learning lazy segment trees
https://github.com/the-hyp0cr1t3/CC/blob/master/%E6%9C%AB%20Snippets/Segment%20trees/Recursive%20%2B%20Range%20updates%20(lazy%20prop).cpp

Is there any generic function that I can write instead of changing every where as I did in above code 

Or how should I do that ( where should I change for mins,max,sum,or gcd,LCM etc for any cumulative functions)

You can explain by taking any example
The default templete is for min i think?

I hope I am clear this time 
Thanks in advance!

**Comment by the-hyp0cr1t3** [comment]
Oh I see, thanks for clarifying. You'll have to make changes in the `Node` struct.

For example, for range max query and range sum  update, it would look something like this:
```c++
const int64_t inf = 2e18;

struct Node {
    using V = int64_t;
    using L = int64_t;

    bool pending{false};
    V val; L lazy{};
    Node(V val = -inf): val(val) {}               // default value
    Node(const Node& l, const Node& r)            // merge two nodes
        : val(std::max(l.val, r.val)) {}
    void apply_lazy(int len) { val += lazy; }     // update node
    operator V() const { return val; }
};
```
Similarly, range gcd query and range assignment updates would look like:
```c++
struct Node {
    using V = int64_t;
    using L = struct Lazy {
        V lzy;
        Lazy(V lzy = 0): lzy(lzy) {}            // default value
        operator V() const { return lzy; }
        void operator+=(const Lazy& rhs) { lzy = rhs.lzy; }    // combine with other lazy
    };

    bool pending{false};
    V val; L lazy{};
    Node(V val = 0): val(val) {}                // default values
    Node(const Node& l, const Node& r)          // merge two nodes
        : val(std::gcd(l.val, r.val)) {}
    void apply_lazy(int len) { val = lazy; }    // update node
    operator V() const { return val; }
};

```

**Comment by MdNihal05** [comment]
hey Thanks !
