### ISSUE TITLE
Ferris Wheel

### ISSUE THREAD

**Issue by mythofsisyphus** [the-hyp0cr1t3/CC#20]
Location CSES/Sorting and Searching/Ferris Wheel.cpp
For n=6, x=20, weights=19, 6, 5, 2, 3, 4
We just need 2 gondolas but here your program says _we need 4._

**Comment by the-hyp0cr1t3** [comment]
> For n=6, x=20, weights=19, 6, 5, 2, 3, 4
> We just need 2 gondolas but here your program says _we need 4._

The [statement](https://cses.fi/problemset/task/1090) mentions the following:

> Each gondola may have one or two children in it

Accordingly, one possible answer to the example provided is:

`[19], [6, 4], [3, 5], [2]`

It can be shown that there is no valid assignment using less than 4 gondolas, which is what the program prints.
